/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, and whether the data API and the model are configured. */
        get: operations["getCityServiceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A short narrated summary of the top three districts for the person's priorities.
         * @description Choose priorities with `persona` (a key from `GET /personas` of the API) or with `weights` (as for `POST /recommend`), or with neither
         *     for the default ranking. The ranking and scores come from `POST /recommend`. `requirements` only tells the model which of the supplied
         *     facts matter to the person. It never changes the ranking.
         */
        post: operations["createAiReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one report from a resident. It is stored as unverified. */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What happens to a report today. */
        get: operations["getFeedbackStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @default pl
         * @enum {string}
         */
        Lang: "pl" | "en";
        Problem: {
            type: string;
            title: string;
            status: number;
            instance?: string;
            detail?: string;
        };
        /**
         * @description The same shape as `Weights` in `backend/openapi.yaml`: category weights 0 to 5 and optional per-metric overrides 0 to 5. The data API
         *     validates the values and rejects unknown categories or metric keys, and this service passes its 422 on.
         */
        Weights: {
            category?: {
                [key: string]: number;
            };
            /** @description Overrides for single metrics, keyed by metric key. */
            metric?: {
                [key: string]: number;
            };
        };
        AiReportRequest: {
            /** @description What matters to the person */
            requirements: string;
            /** @description A key from `GET /personas` of the API. Not together with `weights`. */
            persona?: string;
            /** @description Weights as in `POST /recommend` of the API. Not together with `persona`. */
            weights?: components["schemas"]["Weights"];
            lang?: components["schemas"]["Lang"];
        };
        AiReport: {
            lang: components["schemas"]["Lang"];
            /** @constant */
            ai_generated: true;
            /** @description The AI label to show next to the text */
            label: string;
            model: string;
            /** Format: date-time */
            generated_at: string;
            /** @description The narrated summary. Every number in it is in `facts`. */
            report: string;
            basis: {
                persona: string | null;
                /** @description The weights the ranking used, or null for the default ranking. */
                weights: components["schemas"]["Weights"] | null;
                /** @description Says that scores compare districts of one city only. */
                note: string;
            };
            districts: {
                rank: number;
                code: string;
                name: string;
                score: number;
                /** @description The score as text in `lang`, with that language's decimal mark, for example `62,1 pkt (0-100)`. */
                score_display: string;
            }[];
            /** @description The facts the model was given */
            facts: string[];
        };
        RentPaid: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rent_paid";
            /** @description A district code from the API. */
            district: string;
            /** @description Monthly rent paid */
            rent_pln: number;
            /**
             * @description Flat size in square metres.
             * @enum {string}
             */
            size_band: "up_to_30" | "31_50" | "51_70" | "over_70";
            /** @description The month the rent was paid */
            month: string;
        };
        DataProblem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "data_problem";
            district: string;
            /** @description A metric key from `GET /metrics` of the API. */
            metric_key: string;
            message: string;
        };
        FeedbackReceipt: {
            /** @description A random id. It says nothing about who sent the report. */
            id: string;
            /** @constant */
            status: "unverified";
            /** @constant */
            published: false;
            note: components["schemas"]["Note"];
        };
        FeedbackStatus: {
            accepting: boolean;
            /**
             * @description `not_yet` until the national login exists.
             * @enum {string}
             */
            identity_check: "not_yet" | "gov_id";
            /** @constant */
            stored_as: "unverified";
            /** @constant */
            published: false;
            /** @constant */
            affects_scores: false;
            note: components["schemas"]["Note"];
        };
        /** @description Fixed text in both languages. Not translated at request time. */
        Note: {
            pl: string;
            en: string;
        };
    };
    responses: {
        /** @description The request body is larger than 8 KB (8192 bytes). Nothing was read or stored. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many requests. One shared limit per endpoint, per minute, for all clients (10 for `/ai-report`, 30 for `/feedback`). */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Whole seconds to wait before the next request. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCityServiceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        /** @enum {string} */
                        api: "reachable" | "unreachable";
                        /** @enum {string} */
                        ai: "configured" | "not_configured";
                    };
                };
            };
        };
    };
    createAiReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiReportRequest"];
            };
        };
        responses: {
            /** @description The report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiReport"];
                };
            };
            413: components["responses"]["TooLarge"];
            422: components["responses"]["Problem"];
            429: components["responses"]["TooManyRequests"];
            /** @description The model failed, or its text was dropped because it held a number that is not a fact. Use the stored area report instead. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The model is not configured, or the data API is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RentPaid"] | components["schemas"]["DataProblem"];
            };
        };
        responses: {
            /** @description Stored as unverified. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackReceipt"];
                };
            };
            413: components["responses"]["TooLarge"];
            422: components["responses"]["Problem"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getFeedbackStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The state of the feedback channel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackStatus"];
                };
            };
        };
    };
}
