/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database reachability. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** City, languages, data version, freshness and the attribution lines for the footer. */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All districts with the default livability score and two highlight values. */
        get: operations["listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simplified district boundaries for the map.
         * @description One simplified polygon per district, with the district `code` in `properties`. Cached; changes only when boundaries are reloaded.
         */
        get: operations["getDistrictBoundaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything about one district, grouped by category, with the rank of each metric within the city. */
        get: operations["getDistrict"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stored area report and the default livability score.
         * @description The report is generated at ingestion and stored in both languages. If the Polish text is missing, English is returned and `lang_fallback` is true.
         */
        get: operations["getDistrictReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Districts of the same city with the most similar profile.
         * @description Cosine similarity of the percentile vectors of the scored metrics (the ones the livability score uses). Neutral metrics are not used.
         */
        get: operations["getSimilarDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}/series/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quarterly history of one metric for a district (price charts).
         * @description Only metrics with a stored history are available (the first is `sale_price_median_m2`, quarterly from 2021 in Kraków and from 2022Q4 in Warsaw, because earlier
         *     register records are incomplete). Quarters with fewer deeds than `min_obs` are returned with `low_confidence: true`, never dropped silently.
         */
        get: operations["getDistrictSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}/outlook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price momentum and historical range for a district. No forecast.
         * @description Momentum is read from the stored quarterly district history (`/series`): the change over the last four quarters and since the first stored
         *     quarter. The historical range is the spread of past one- and two-year price changes in the whole city (NBP data), shown as history.
         *     **No forward scenario is published:** the backtest in `scenario.backtest` shows that no tested method beat the naive baselines, so
         *     `scenario.published` is false. If a later method passes, `published` becomes true and `scenario.ranges` is filled. Never a single number,
         *     never a ranking of districts by predicted growth, not financial advice.
         */
        get: operations["getDistrictOutlook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{code}/rent-vs-buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gross yield and payback for a flat of a given size (stateless calculation).
         * @description Uses the stored district medians: price = sale price per m2 x area, rent = rent per m2 x area, yield = rent x 12 / price,
         *     payback = price / (rent x 12). Asking rent over transaction price; no mortgage, tax, costs or price change. Values are `estimated`.
         */
        get: operations["getRentVsBuy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The metric catalogue with availability in this city. */
        get: operations["listMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{key}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One metric for all districts (choropleth and sorting), with rank. */
        get: operations["getMetricValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Side-by-side values of two to four districts. */
        get: operations["compareDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public-transport time from one district to every district.
         * @description Read from a precomputed table: simple routing over the city's GTFS, one representative weekday morning, district centroids, walking to
         *     and from stops. Values are `estimated` and describe typical access between areas, not a journey plan.
         */
        get: operations["getCommute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Named weight presets for the recommender. */
        get: operations["listPersonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank the districts for the user's weights and explain the ranking.
         * @description Percentile ranks within the city, 100 = best, weighted as requested and renormalised. Without weights the result equals the stored
         *     `livability_score_default`. Neutral metrics and composite indices are never inputs. Metrics without data in this city are ignored and
         *     listed in `missing_metrics`.
         */
        post: operations["recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Lang: "en" | "pl";
        /** @description Stable slug of the district, for example `srodmiescie`. */
        DistrictCode: string;
        /** @enum {string} */
        Category: "transport" | "demographics" | "livability" | "amenities" | "environment" | "cost" | "safety";
        /**
         * @description Measured or officially reported, calculated from real inputs, or an indirect indicator. Show it beside every value.
         * @enum {string}
         */
        DataKind: "observed" | "estimated" | "proxy";
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "reachable" | "unreachable";
        };
        Source: {
            name: string;
            /** Format: uri */
            url?: string;
            licence: string;
            /** @description The credit line the source requires; show it beside the value or in the footer. */
            attribution: string;
        };
        Meta: {
            /** @example warsaw */
            city: string;
            /** @example Warszawa */
            city_name?: string;
            default_lang: components["schemas"]["Lang"];
            languages: components["schemas"]["Lang"][];
            district_count: number;
            /** @description Hash of the latest fetch times and report versions; also the ETag source. */
            data_version: string;
            /** Format: date-time */
            latest_ingestion_run?: string | null;
            stale: {
                is_stale: boolean;
                /** @description For example a failed audit, reports older than their data, or a weekly source that did not refresh. */
                reasons: string[];
            };
            /** @description One entry per source in use, with the newest as-of date, for the footer. */
            sources: (components["schemas"]["Source"] & {
                /** Format: date */
                as_of?: string;
                metric_keys?: string[];
            })[];
            score_note?: string;
        };
        Rank: {
            /** @description 1 is the best district after applying the direction. */
            position: number;
            of: number;
            /** @enum {string} */
            direction: "higher is better" | "lower is better";
        };
        /**
         * @example {
         *       "key": "crimes_per_10k",
         *       "label": "Recorded crimes per 10,000 residents",
         *       "display": "862 per 10,000 residents",
         *       "value": 862.5,
         *       "unit": "per 10,000",
         *       "data_kind": "observed",
         *       "n_obs": 8299,
         *       "as_of": "2024-12-31",
         *       "source": {
         *         "name": "Panorama dzielnic Warszawy w 2024 r.",
         *         "licence": "Public statistics of Urząd Statystyczny w Warszawie (source must be cited)",
         *         "attribution": "Urząd Statystyczny w Warszawie, Panorama dzielnic Warszawy w 2024 r.; crime data: Komenda Główna Policji"
         *       },
         *       "caveat": "Recorded crimes, not risk. Inflated in districts with many visitors and commuters.",
         *       "rank": {
         *         "position": 18,
         *         "of": 18,
         *         "direction": "lower is better"
         *       }
         *     }
         */
        MetricValue: {
            key: string;
            /**
             * @default true
             * @constant
             */
            available: true;
            label: string;
            /** @description The stored display string in the requested language. Clients never format numbers. */
            display: string;
            value: number;
            unit?: string;
            data_kind: components["schemas"]["DataKind"];
            /** @description Sample size behind the value; a small number means low confidence. */
            n_obs?: number | null;
            /** Format: date */
            as_of: string;
            /**
             * Format: date-time
             * @description Only for weekly-refresh metrics.
             */
            updated_at?: string | null;
            source: components["schemas"]["Source"];
            method?: string;
            caveat?: string | null;
            /** @description Omitted for neutral metrics, which are shown but never ranked. */
            rank?: components["schemas"]["Rank"];
        };
        UnavailableMetric: {
            key: string;
            /** @constant */
            available: false;
            label?: string;
            /** @description Why this city has no data for the metric. Stored as data, in the requested language. */
            reason: string;
        };
        MetricEntry: components["schemas"]["MetricValue"] | components["schemas"]["UnavailableMetric"];
        CategoryGroup: {
            category: components["schemas"]["Category"];
            label: string;
            metrics: components["schemas"]["MetricEntry"][];
        };
        Highlight: {
            key: string;
            display: string;
            data_kind: components["schemas"]["DataKind"];
        };
        DistrictListItem: {
            code: components["schemas"]["DistrictCode"];
            /** @description A proper noun; the same in both languages. */
            name: string;
            area_km2: number;
            livability_score: number | null;
            /** @description Sale price and rent per m2, so the map list loads fast. */
            highlights: components["schemas"]["Highlight"][];
        };
        DistrictDetail: {
            code: components["schemas"]["DistrictCode"];
            name: string;
            area_km2: number;
            lang: components["schemas"]["Lang"];
            livability_score: number | null;
            score_note?: string;
            categories: components["schemas"]["CategoryGroup"][];
            /** @description Gross rental yield (rent x 12 / price) from the district medians; null if either input is missing. */
            yield_gross?: components["schemas"]["MetricValue"] | null;
            payback_years?: components["schemas"]["MetricValue"] | null;
        };
        BoundaryCollection: {
            /** @constant */
            type: "FeatureCollection";
            features: {
                /** @constant */
                type: "Feature";
                /** @description A GeoJSON Polygon or MultiPolygon, simplified. */
                geometry: Record<string, never>;
                properties: {
                    code: components["schemas"]["DistrictCode"];
                    name: string;
                };
            }[];
        };
        Report: {
            district: components["schemas"]["DistrictCode"];
            lang: components["schemas"]["Lang"];
            /** @description True if the requested language was missing and English is returned. */
            lang_fallback: boolean;
            livability_score: number | null;
            body: string;
            model?: string;
            /** Format: date-time */
            generated_at: string;
            estimated_or_proxy_values_flagged?: boolean;
        };
        MetricDefinition: {
            key: string;
            category: components["schemas"]["Category"];
            label: string;
            description: string;
            unit: string;
            /** @enum {string} */
            higher_is: "better" | "worse" | "neutral";
            /** @enum {string} */
            refresh_cadence: "weekly" | "static";
            data_kind: components["schemas"]["DataKind"];
            /** @description False if this city has no data for the metric. */
            available: boolean;
            /** @description Set when `available` is false. */
            reason?: string | null;
            /** @description True if `/districts/{code}/series/{key}` returns history. */
            has_series?: boolean;
        };
        MetricValues: {
            key: string;
            label?: string;
            lang: components["schemas"]["Lang"];
            /** @enum {string} */
            higher_is?: "better" | "worse" | "neutral";
            /**
             * @example [
             *       {
             *         "district": "zoliborz",
             *         "value": 22434,
             *         "display": "22,434 PLN/m²"
             *       },
             *       {
             *         "district": "srodmiescie",
             *         "value": 21117,
             *         "display": "21,117 PLN/m²"
             *       }
             *     ]
             */
            values: {
                district: components["schemas"]["DistrictCode"];
                value: number;
                display: string;
                data_kind?: components["schemas"]["DataKind"];
                n_obs?: number | null;
                rank?: components["schemas"]["Rank"];
            }[];
        };
        Series: {
            district: components["schemas"]["DistrictCode"];
            key: string;
            label?: string;
            lang: components["schemas"]["Lang"];
            unit?: string;
            data_kind?: components["schemas"]["DataKind"];
            /** @description Quarters with fewer observations are marked low confidence. Proposal 30. */
            min_obs: number;
            source?: components["schemas"]["Source"];
            method?: string;
            caveat?: string | null;
            points: {
                /** Format: date */
                period_start: string;
                /** Format: date */
                period_end: string;
                value: number;
                display: string;
                n_obs: number;
                low_confidence: boolean;
            }[];
        };
        Outlook: {
            district: components["schemas"]["DistrictCode"];
            lang: components["schemas"]["Lang"];
            /** @constant */
            data_kind?: "observed";
            momentum: {
                /** @description Null if the history has no quarter one year before the newest one. */
                growth_12m: components["schemas"]["Growth"] | null;
                growth_since_start: components["schemas"]["Growth"] | null;
            };
            /** @description How much prices in the whole city changed over past windows. A record of the past, not a forecast. */
            city_history: {
                available: boolean;
                /** Format: date */
                period_start?: string;
                /** Format: date */
                period_end?: string;
                windows?: {
                    /** @description Length of the window: 4 or 8 quarters. */
                    quarters: number;
                    label: string;
                    /** @description 10th percentile of past price changes, as a fraction. */
                    low: number;
                    median: number;
                    /** @description 90th percentile. */
                    high: number;
                    low_display: string;
                    median_display: string;
                    high_display: string;
                    /** @description Overlapping windows behind the figures; far fewer are independent. */
                    n_windows: number;
                }[];
                source?: components["schemas"]["Source"];
                method?: string;
            };
            scenario: {
                /** @description False while no tested method passes the backtest. */
                published: boolean;
                reason: string;
                /** @description Reserved for a passing method; empty while `published` is false. */
                ranges?: unknown[];
                backtest?: {
                    /** Format: date */
                    period_start?: string;
                    /** Format: date */
                    period_end?: string;
                    cities?: number;
                    results?: {
                        quarters: number;
                        method: string;
                        origins?: number;
                        /** @description Median absolute error of the method, in log growth. */
                        mae_method: number;
                        mae_no_change: number;
                        mae_last_year_continues: number;
                        /** @description Share of outcomes inside the 10th-90th percentile range; 0.8 is ideal. */
                        coverage_80: number;
                        passes: boolean;
                    }[];
                };
            };
            method: string;
            caveat: string;
        };
        Growth: {
            /** @description Change as a fraction, for example 0.05 for +5 percent. */
            value: number;
            display: string;
            /** @description Per-year rate; only for growth since the first stored quarter. */
            annualised?: number | null;
            annualised_display?: string | null;
            /**
             * Format: date
             * @description Start of the first quarter compared.
             */
            from: string;
            /**
             * Format: date
             * @description Start of the second quarter compared.
             */
            to: string;
            from_display: string;
            to_display: string;
            n_obs_from?: number;
            n_obs_to?: number;
            /** @description True if either quarter has fewer deeds than `min_obs` of the series. */
            low_confidence: boolean;
        };
        RentVsBuy: {
            district: components["schemas"]["DistrictCode"];
            lang: components["schemas"]["Lang"];
            area_m2: number;
            price: components["schemas"]["Amount"];
            monthly_rent: components["schemas"]["Amount"];
            /** @description A fraction, for example 0.055 for 5.5 percent. */
            yield_gross: number;
            yield_display?: string;
            payback_years: number;
            payback_display?: string;
            /** @constant */
            data_kind: "estimated";
            /** @description The stored medians used, with counts in `n_obs` of each. */
            based_on?: components["schemas"]["Highlight"][];
            /** @description Asking rent over transaction price; no mortgage, tax, costs or price change. */
            caveat: string;
        };
        Amount: {
            value: number;
            /** @default PLN */
            currency: string;
            display: string;
        };
        Commute: {
            from: components["schemas"]["DistrictCode"];
            lang: components["schemas"]["Lang"];
            /** @constant */
            data_kind?: "estimated";
            method: string;
            /** Format: date */
            as_of: string;
            caveat?: string;
            destinations: {
                code: components["schemas"]["DistrictCode"];
                /** @description Null if no public-transport connection was found within the search limit. */
                minutes: number | null;
            }[];
        };
        Persona: {
            /** @example student */
            key: string;
            label: string;
            description: string;
            weights: components["schemas"]["Weights"];
        };
        /**
         * @description Category weights 0 to 5 and optional per-metric overrides 0 to 5. Direction is fixed by the catalogue; negative weights are rejected.
         *     Weights scale the default weights, which give every category the same total: a category not mentioned counts as 1, a metric not
         *     mentioned as 1, 0 leaves a category or metric out, 5 counts five times as much. A metric override multiplies that metric's share
         *     inside its category. With no weights the result equals the stored default livability score. Metrics that are not scored (neutral
         *     or composite) and unknown keys are rejected.
         */
        Weights: {
            category?: {
                [key: string]: number;
            };
            /** @description Overrides for single metrics, keyed by metric key. Unknown keys are rejected. */
            metric?: {
                [key: string]: number;
            };
        };
        RecommendRequest: {
            weights?: components["schemas"]["Weights"];
            lang?: components["schemas"]["Lang"];
        };
        RecommendResponse: {
            lang: components["schemas"]["Lang"];
            weights_normalised: boolean;
            metrics_used: number;
            missing_metrics: string[];
            /** @description Says that scores compare districts of this city only. */
            note: string;
            ranking: {
                rank: number;
                code: components["schemas"]["DistrictCode"];
                name: string;
                score: number;
                /** @description Metrics that contribute most to this district's score under the given weights. */
                top_drivers: {
                    key: string;
                    label?: string;
                    percentile: number;
                }[];
            }[];
        };
    };
    responses: {
        /** @description Error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
        Lang: components["schemas"]["Lang"];
        DistrictCode: components["schemas"]["DistrictCode"];
        MetricKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Derived from `data_version`. Send it back in `If-None-Match` to get 304. */
        ETag: string;
        /** @description `public, max-age=300`; shorter for weekly-refresh metrics. */
        CacheControl: string;
        /** @description Present when the data is stale or the last audit failed. The reasons are in `/meta` under `stale`. */
        DataWarning: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMeta: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata of this deployment. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listDistricts: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Districts of the city (18 for Warsaw and for Krakow). */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Data-Warning": components["headers"]["DataWarning"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lang: components["schemas"]["Lang"];
                        /** @description Always says that scores compare districts of this city only. */
                        score_note: string;
                        districts: components["schemas"]["DistrictListItem"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDistrictBoundaries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A GeoJSON FeatureCollection. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["BoundaryCollection"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDistrict: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The district. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Data-Warning": components["headers"]["DataWarning"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictDetail"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getDistrictReport: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-Data-Warning": components["headers"]["DataWarning"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getSimilarDistricts: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
                limit?: number;
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Similar districts, most similar first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        district: components["schemas"]["DistrictCode"];
                        lang: components["schemas"]["Lang"];
                        method: string;
                        similar: {
                            code: components["schemas"]["DistrictCode"];
                            name: string;
                            similarity: number;
                            /** @description Metric keys where the two districts are closest. */
                            closest_on?: string[];
                        }[];
                    };
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getDistrictSeries: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
                key: components["parameters"]["MetricKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The series. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getDistrictOutlook: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The outlook. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Outlook"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getRentVsBuy: {
        parameters: {
            query: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
                area_m2: number;
            };
            header?: never;
            path: {
                code: components["parameters"]["DistrictCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentVsBuy"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listMetrics: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All catalogue metrics, including those without data here. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lang: components["schemas"]["Lang"];
                        metrics: components["schemas"]["MetricDefinition"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMetricValues: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                key: components["parameters"]["MetricKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Values, best first for directional metrics, else in descending order. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    "X-Data-Warning": components["headers"]["DataWarning"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricValues"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    compareDistricts: {
        parameters: {
            query: {
                /** @description Comma-separated district codes, two to four. */
                codes: string;
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chosen districts in the request order, same metric shape as the district detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lang: components["schemas"]["Lang"];
                        districts: components["schemas"]["DistrictDetail"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getCommute: {
        parameters: {
            query: {
                from: components["schemas"]["DistrictCode"];
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minutes to each destination district. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commute"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listPersonas: {
        parameters: {
            query?: {
                /** @description Response language. If absent, the `Accept-Language` header is used, then English. Every response echoes the language used in `lang`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presets, stored as data. Send `weights` to `/recommend` as they are, or let the user adjust them. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lang: components["schemas"]["Lang"];
                        personas: components["schemas"]["Persona"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Ranked districts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
