-- Seed of the metric catalogue: the metric_keys the data team must produce. Polish labels are a first
-- draft and need a native-speaker review. Identical in both city schemas.
insert into krakow.metric_definitions
  (metric_key, category, label_en, label_pl, description_en, unit, higher_is, refresh_cadence, default_data_kind, sort_order)
values
  ('transit_stops_total', 'transport', 'Public transport stops', 'Przystanki komunikacji miejskiej', 'All bus, tram and rail stops inside the district (GTFS).', 'stops', 'better', 'static', 'observed', 10),
  ('transit_stops_bus', 'transport', 'Bus stops', 'Przystanki autobusowe', null, 'stops', 'better', 'static', 'observed', 20),
  ('transit_stops_tram', 'transport', 'Tram stops', 'Przystanki tramwajowe', null, 'stops', 'better', 'static', 'observed', 30),
  ('transit_stops_rail_metro', 'transport', 'Rail and metro stations', 'Stacje kolejowe i metra', 'Rail stations and, in Warsaw, metro stations.', 'stations', 'better', 'static', 'observed', 40),
  ('transit_routes_count', 'transport', 'Routes serving the district', 'Linie obsługujące dzielnicę', null, 'routes', 'better', 'static', 'observed', 50),
  ('transit_departures_weekday', 'transport', 'Weekday departures', 'Odjazdy w dzień roboczy', 'Scheduled departures from the district''s stops on a typical weekday.', 'departures/day', 'better', 'static', 'observed', 60),
  ('transit_night_departures', 'transport', 'Night departures', 'Odjazdy nocne', 'Scheduled departures between 23:00 and 05:00.', 'departures/night', 'better', 'static', 'observed', 70),
  ('airport_distance_km', 'transport', 'Distance to the airport', 'Odległość od lotniska', 'Straight-line distance from the district centre to the main airport.', 'km', 'worse', 'static', 'observed', 80),
  ('population_total', 'demographics', 'Population', 'Liczba ludności', null, 'people', 'neutral', 'static', 'observed', 90),
  ('residents_registered', 'demographics', 'Registered permanent residents', 'Zameldowani na pobyt stały', 'People registered for permanent residence. Not the same as total population.', 'people', 'neutral', 'static', 'observed', 100),
  ('population_density', 'demographics', 'Population density', 'Gęstość zaludnienia', null, 'people/km²', 'neutral', 'static', 'observed', 110),
  ('age_mean', 'demographics', 'Average age', 'Średni wiek', null, 'years', 'neutral', 'static', 'observed', 120),
  ('share_age_65_plus', 'demographics', 'Residents aged 65 or older', 'Mieszkańcy w wieku 65+', null, '%', 'neutral', 'static', 'observed', 130),
  ('share_female', 'demographics', 'Share of women', 'Udział kobiet', null, '%', 'neutral', 'static', 'observed', 140),
  ('amenity_schools', 'amenities', 'Schools', 'Szkoły', 'Schools mapped in OpenStreetMap.', 'count', 'better', 'static', 'observed', 150),
  ('amenity_hospitals_clinics', 'amenities', 'Hospitals and clinics', 'Szpitale i przychodnie', null, 'count', 'better', 'static', 'observed', 160),
  ('amenity_parks_share', 'amenities', 'Park area', 'Powierzchnia parków', null, '% of district', 'better', 'static', 'observed', 170),
  ('amenity_supermarkets', 'amenities', 'Supermarkets', 'Supermarkety', null, 'count', 'better', 'static', 'observed', 180),
  ('amenity_malls', 'amenities', 'Shopping centres', 'Centra handlowe', null, 'count', 'better', 'static', 'observed', 190),
  ('amenity_gyms', 'amenities', 'Gyms and fitness clubs', 'Siłownie i kluby fitness', null, 'count', 'better', 'static', 'observed', 200),
  ('amenity_parking', 'amenities', 'Car parks', 'Parkingi', null, 'count', 'neutral', 'static', 'observed', 210),
  ('air_pm10_mean', 'environment', 'PM10 (annual mean)', 'Pył PM10 (średnia roczna)', 'Interpolated between GIOŚ stations; not address-level exposure.', 'µg/m³', 'worse', 'weekly', 'estimated', 220),
  ('air_pm25_mean', 'environment', 'PM2.5 (annual mean)', 'Pył PM2,5 (średnia roczna)', null, 'µg/m³', 'worse', 'weekly', 'estimated', 230),
  ('air_no2_mean', 'environment', 'NO₂ (annual mean)', 'Dwutlenek azotu NO₂ (średnia roczna)', null, 'µg/m³', 'worse', 'weekly', 'estimated', 240),
  ('air_quality_index', 'environment', 'Air quality index (latest)', 'Indeks jakości powietrza (ostatni)', 'GIOŚ index from 0 (very good) to 5 (very bad), latest reading, interpolated between stations.', 'index 0-5', 'worse', 'weekly', 'estimated', 250),
  ('tree_cover_share', 'environment', 'Tree cover', 'Pokrycie drzewami', 'Copernicus Tree Cover Density.', '% of district', 'better', 'static', 'observed', 260),
  ('green_space_share', 'environment', 'Green space', 'Tereny zielone', 'Copernicus Urban Atlas green urban areas and forests.', '% of district', 'better', 'static', 'observed', 270),
  ('heat_exposure_index', 'environment', 'Summer heat exposure', 'Ekspozycja na upał latem', 'Built-up share against tree cover.', 'index', 'worse', 'static', 'proxy', 280),
  ('noise_share_above_55db', 'livability', 'Area above 55 dB', 'Powierzchnia powyżej 55 dB', 'Strategic noise map, Lden.', '% of district', 'worse', 'static', 'observed', 290),
  ('night_noise_estimate', 'livability', 'Night noise (estimate)', 'Hałas nocny (szacunek)', 'From nightlife density, road class and rail.', 'index', 'worse', 'static', 'proxy', 300),
  ('nightlife_density', 'livability', 'Bars and clubs', 'Bary i kluby', null, 'per km²', 'neutral', 'static', 'observed', 310),
  ('busyness_index', 'livability', 'Busyness', 'Natężenie ruchu i tłum', 'From shop, venue and stop density.', 'index', 'neutral', 'static', 'proxy', 320),
  ('walkability_index', 'livability', 'Walkability', 'Dostępność pieszo', 'Daily needs within a 10-minute walk.', 'index', 'better', 'static', 'proxy', 330),
  ('family_friendliness_index', 'livability', 'Family friendliness', 'Przyjazność dla rodzin', null, 'index', 'better', 'static', 'proxy', 340),
  ('sale_price_median_m2', 'cost', 'Median sale price per m²', 'Mediana ceny sprzedaży za m²', 'Notarised transactions (RCN), last 12 to 24 months.', 'PLN/m²', 'worse', 'static', 'observed', 350),
  ('sale_transactions_count', 'cost', 'Sale transactions counted', 'Liczba uwzględnionych transakcji', null, 'count', 'neutral', 'static', 'observed', 360),
  ('rent_price_median_m2', 'cost', 'Median rent per m²', 'Mediana czynszu za m²', 'One-time listing snapshot.', 'PLN/m²', 'worse', 'static', 'observed', 370),
  ('rent_listings_count', 'cost', 'Rent listings counted', 'Liczba uwzględnionych ofert najmu', null, 'count', 'neutral', 'static', 'observed', 380),
  ('crimes_per_10k', 'safety', 'Recorded crimes per 10,000 residents', 'Przestępstwa stwierdzone na 10 000 mieszkańców', 'Police-recorded crimes. Inflated in tourist and commuter districts.', 'per 10,000', 'worse', 'static', 'observed', 390),
  ('crime_detection_rate', 'safety', 'Offender detection rate', 'Wskaźnik wykrywalności sprawców', null, '%', 'better', 'static', 'observed', 400),
  ('road_accidents_per_km', 'safety', 'Road accidents per km of road', 'Wypadki drogowe na km dróg', 'Police SEWiK data.', 'per km', 'worse', 'static', 'observed', 410),
  ('road_ped_cyc_casualties_per_km', 'safety', 'Pedestrian and cyclist casualties per km', 'Poszkodowani piesi i rowerzyści na km', null, 'per km', 'worse', 'static', 'observed', 420),
  ('lit_street_share', 'safety', 'Streets tagged as lit', 'Ulice oznaczone jako oświetlone', 'OpenStreetMap lit=yes. Weak signal.', '%', 'better', 'static', 'proxy', 430),
  ('emergency_services_distance_km', 'safety', 'Distance to police, fire and hospital', 'Odległość do policji, straży i szpitala', null, 'km', 'worse', 'static', 'proxy', 440),
  ('safety_index', 'safety', 'Safety index (composite)', 'Wskaźnik bezpieczeństwa (złożony)', 'Weighted percentile ranks of the safety metrics above.', 'index', 'better', 'static', 'estimated', 450),
  ('livability_score_default', 'livability', 'Livability score (equal weights)', 'Ocena warunków życia (równe wagi)', 'Weighted percentile ranks across all categories. Computed in code.', 'score', 'better', 'static', 'estimated', 460)
on conflict (metric_key) do update set
  category=excluded.category, label_en=excluded.label_en, label_pl=excluded.label_pl,
  description_en=excluded.description_en, unit=excluded.unit, higher_is=excluded.higher_is,
  refresh_cadence=excluded.refresh_cadence, default_data_kind=excluded.default_data_kind, sort_order=excluded.sort_order;
