-- Plain units and Polish texts for sources, licences and units (issue: reviewers found English units and licence texts in the Polish view).
-- 1. metric_definitions.unit becomes a plain English noun ("schools", "shops") instead of the same word "count" for twelve different metrics.
--    The Polish version of each unit is stored below, and the API shows it for lang=pl. The row-level unit of district_metrics is no longer shown.
-- 2. The Polish version of every source name, licence text and credit line that was English only is added to translation_cache, which the API
--    already uses for notes (English text -> Polish text). A text with no entry is shown as stored. Rows are marked engine = 'manual'.
-- Safe to re-run. UPDATEs on metric_definitions are recorded in krakow.audit_log, so the old units can be restored from it. Polish text needs a native check.

update krakow.metric_definitions m
   set unit = v.unit
  from (values
    ('transit_stops_total', 'stops'),
    ('transit_stops_bus', 'stops'),
    ('transit_stops_tram', 'stops'),
    ('transit_stops_rail_metro', 'stations'),
    ('transit_routes_count', 'lines'),
    ('transit_departures_weekday', 'departures a day'),
    ('transit_night_departures', 'departures a night'),
    ('airport_distance_km', 'km'),
    ('population_total', 'people'),
    ('residents_registered', 'people'),
    ('population_density', 'people per km²'),
    ('age_mean', 'years'),
    ('share_age_65_plus', '% of residents'),
    ('share_female', '% of residents'),
    ('amenity_schools', 'schools'),
    ('amenity_hospitals_clinics', 'facilities'),
    ('amenity_parks_share', '% of district area'),
    ('amenity_supermarkets', 'shops'),
    ('amenity_malls', 'malls'),
    ('amenity_gyms', 'gyms'),
    ('amenity_parking', 'car parks'),
    ('amenity_open_sports_grounds', 'school sites'),
    ('amenity_nursery_places', 'places'),
    ('amenity_restaurants_cafes', 'venues'),
    ('air_pm10_mean', 'µg/m³'),
    ('air_pm25_mean', 'µg/m³'),
    ('air_no2_mean', 'µg/m³'),
    ('air_quality_index', 'scale 0-5'),
    ('tree_cover_share', '% of district area'),
    ('green_space_share', '% of district area'),
    ('heat_exposure_index', 'scale 0-100'),
    ('noise_share_above_55db', '% of district area'),
    ('night_noise_estimate', 'scale 0-100'),
    ('nightlife_density', 'per km²'),
    ('busyness_index', 'scale 0-100'),
    ('walkability_index', 'scale 0-100'),
    ('family_friendliness_index', 'scale 0-100'),
    ('safety_index', 'scale 0-100'),
    ('sale_price_median_m2', 'PLN per m²'),
    ('sale_transactions_count', 'transactions'),
    ('rent_price_median_m2', 'PLN per m² a month'),
    ('rent_listings_count', 'listings'),
    ('nursery_fee_median', 'PLN a month'),
    ('crimes_per_10k', 'per 10,000 residents'),
    ('crime_detection_rate', '%'),
    ('road_accidents_per_km', 'per km of road a year'),
    ('road_ped_cyc_casualties_per_km', 'per km of road a year'),
    ('lit_street_share', '% of road length'),
    ('emergency_services_distance_km', 'km'),
    ('amenity_aed_public', 'defibrillators'),
    ('livability_score_default', 'points (0-100)')
  ) as v(metric_key, unit)
 where m.metric_key = v.metric_key and m.unit is distinct from v.unit;

insert into krakow.translation_cache (cache_key, source_lang, target_lang, source_text, translated_text, engine, model, glossary_version)
select encode(sha256(convert_to('manual|en|pl|' || v.en, 'UTF8')), 'hex'), 'en', 'pl', v.en, v.pl, 'manual', 'manual', '1'
  from (values
    ('% of district area', '% powierzchni dzielnicy'),
    ('% of residents', '% mieszkańców'),
    ('% of road length', '% długości dróg'),
    ('PLN a month', 'zł miesięcznie'),
    ('PLN per m²', 'zł za m²'),
    ('PLN per m² a month', 'zł za m² miesięcznie'),
    ('car parks', 'parkingi'),
    ('defibrillators', 'defibrylatory'),
    ('departures a day', 'odjazdy na dobę'),
    ('departures a night', 'odjazdy w nocy'),
    ('facilities', 'placówki'),
    ('gyms', 'siłownie'),
    ('lines', 'linie'),
    ('listings', 'oferty'),
    ('malls', 'centra handlowe'),
    ('people', 'osoby'),
    ('people per km²', 'osób na km²'),
    ('per 10,000 residents', 'na 10 tys. mieszkańców'),
    ('per km of road a year', 'na km dróg rocznie'),
    ('per km²', 'na km²'),
    ('places', 'miejsca'),
    ('points (0-100)', 'pkt (0–100)'),
    ('scale 0-100', 'skala 0–100'),
    ('scale 0-5', 'skala 0–5'),
    ('school sites', 'placówki'),
    ('schools', 'szkoły'),
    ('shops', 'sklepy'),
    ('stations', 'stacje'),
    ('stops', 'przystanki'),
    ('transactions', 'transakcje'),
    ('venues', 'lokale'),
    ('years', 'lata'),
    ('Derived from loaded metrics', 'Obliczone z pozostałych miar'),
    ('GdzieZamieszkac, computed from the metrics'' sources', 'GdzieZamieszkać, obliczone ze źródeł wymienionych miar'),
    ('Derived; inherits the licences of its inputs', 'Dane pochodne; dziedziczą licencje danych źródłowych'),
    ('GIOŚ air quality index (current)', 'Indeks jakości powietrza GIOŚ (aktualny)'),
    ('GIOŚ air quality stations (archival data)', 'Stacje pomiarowe jakości powietrza GIOŚ (dane archiwalne)'),
    ('Open data of GIOŚ (Państwowy Monitoring Środowiska); attribution required', 'Dane otwarte GIOŚ (Państwowy Monitoring Środowiska); wymagane podanie źródła'),
    ('Copernicus HRL Tree Cover Density 10 m', 'Copernicus: gęstość pokrycia drzewami (HRL, 10 m)'),
    ('Copernicus Land Monitoring Service: free, full and open access (attribution: Copernicus Land Monitoring Service, European Environment Agency)', 'Copernicus Land Monitoring Service: pełny, otwarty i bezpłatny dostęp (podpis: Copernicus Land Monitoring Service, European Environment Agency)'),
    ('Public information (BIP, Urząd Miasta Krakowa); reuse of public sector information', 'Informacja publiczna (BIP, Urząd Miasta Krakowa); ponowne wykorzystanie informacji sektora publicznego'),
    ('Kraków open data: residents registered for permanent residence by age and sex', 'Otwarte dane Krakowa: zameldowani na pobyt stały według wieku i płci'),
    ('Open data of Urząd Miasta Krakowa (otwartedane.um.krakow.pl); check the dataset page for the licence before redistribution', 'Dane otwarte Urzędu Miasta Krakowa (otwartedane.um.krakow.pl); przed ponownym udostępnianiem sprawdź licencję na stronie zbioru danych'),
    ('Kraków strategic noise map 2022 (Lden)', 'Strategiczna mapa hałasu Krakowa 2022 (Lden)'),
    ('Open data of Miasto Kraków (strategic noise map 2022, public map service); check reuse terms before redistribution', 'Dane otwarte Miasta Kraków (strategiczna mapa hałasu 2022, publiczna usługa mapowa); przed ponownym udostępnianiem sprawdź warunki wykorzystania'),
    ('National register of nurseries and children''s clubs', 'Krajowy rejestr żłobków i klubów dziecięcych'),
    ('OpenStreetMap via Overpass', 'OpenStreetMap (przez Overpass)'),
    ('Otodom and OLX flat rent listings (snapshot)', 'Ogłoszenia o wynajmie mieszkań z Otodom i OLX (jednorazowy zrzut)'),
    ('Public Otodom and OLX listings, one-time snapshot for internal analysis; not redistributed', 'Publiczne ogłoszenia Otodom i OLX, jednorazowy zrzut do użytku wewnętrznego; nie są dalej udostępniane'),
    ('Otodom and OLX (asking rents, snapshot)', 'Otodom i OLX (czynsze ofertowe, jednorazowy zrzut)'),
    ('Public transport GTFS feeds', 'Dane rozkładowe komunikacji miejskiej (GTFS)'),
    ('Open data published by ZTP Kraków / MPK (no licence text found on the feed page)', 'Dane otwarte publikowane przez ZTP Kraków / MPK (na stronie danych nie znaleziono tekstu licencji)'),
    ('Open data, no access constraints (GUGiK RCN WFS)', 'Dane otwarte, bez ograniczeń dostępu (GUGiK, usługa WFS RCN)'),
    ('SEWiK police accident register (sewik.pl dump)', 'Policyjny rejestr wypadków SEWiK (kopia z sewik.pl)'),
    ('Police SEWiK data via Polskie Obserwatorium BRD: non-commercial use free, credit required, commercial use needs written approval', 'Dane policyjne SEWiK przez Polskie Obserwatorium BRD: użytek niekomercyjny bezpłatny, wymagane podanie źródła, użytek komercyjny wymaga pisemnej zgody'),
    ('NBP public statistics, free download; source must be cited. Reuse terms not reviewed.', 'Statystyka publiczna NBP, bezpłatne pobieranie; należy podać źródło. Warunki ponownego wykorzystania nie zostały sprawdzone.')
  ) as v(en, pl)
on conflict (cache_key) do update set translated_text = excluded.translated_text, engine = excluded.engine, model = excluded.model;
