-- Plain-language names and descriptions for the metric catalogue, after the reviewers' feedback (jargon such as PM10, NO2, "median", "index",
-- "routes", and mentions of Warsaw in a Kraków catalogue). A label says what the figure is; a description says what it means and how to read it.
-- The two metrics that gain Kraków data (school sports grounds, defibrillators) are changed in the migration that loads that data.
-- Safe to re-run. UPDATEs are recorded in krakow.audit_log (old and new row), so the earlier texts can be restored. Polish text needs a native check.

update krakow.metric_definitions m
   set label_en = v.label_en, label_pl = v.label_pl, description_en = v.description_en, description_pl = v.description_pl
  from (values
    ('transit_stops_total', 'Stops in the district', 'Przystanki w dzielnicy', 'How many bus, tram and other public transport stops the district has. A stop with several platforms counts once. From the timetables.', 'Ile przystanków autobusowych, tramwajowych i innych ma dzielnica. Przystanek z kilkoma peronami liczy się raz. Dane z rozkładów jazdy.'),
    ('transit_routes_count', 'Lines that run through the district', 'Linie, które jeżdżą przez dzielnicę', 'How many different lines (route numbers) have at least one stop in the district. This is not the number of stops: one line stops at many stops.', 'Ile różnych linii (numerów) ma co najmniej jeden przystanek w dzielnicy. To nie jest liczba przystanków: jedna linia zatrzymuje się na wielu przystankach.'),
    ('transit_departures_weekday', 'Departures on a weekday', 'Odjazdy w dzień roboczy', 'How many times on a normal weekday a bus or tram leaves the district''s stops, by the timetable (Tuesday 6 October 2026). More means more frequent service.', 'Ile razy w zwykły dzień roboczy autobus lub tramwaj odjeżdża z przystanków dzielnicy, według rozkładu (wtorek 6 października 2026). Więcej oznacza częstsze kursy.'),
    ('transit_night_departures', 'Night departures', 'Odjazdy w nocy', 'How many times between 23:00 and 04:59 on that weekday a bus or tram leaves the district''s stops, by the timetable.', 'Ile razy między 23:00 a 4:59 w tym dniu roboczym autobus lub tramwaj odjeżdża z przystanków dzielnicy, według rozkładu.'),
    ('transit_stops_rail_metro', 'Rail and metro stations', 'Stacje kolejowe i metra', 'Rail and metro stations in the timetable data. No data for Kraków: the city''s timetable data contains no rail.', 'Stacje kolejowe i metra z danych rozkładowych. Brak danych dla Krakowa: miejskie dane rozkładowe nie zawierają kolei.'),
    ('airport_distance_km', 'Distance to the airport', 'Odległość od lotniska', 'Straight-line distance from the middle of the district to Kraków Airport (Balice). It is not a travel time.', 'Odległość w linii prostej od środka dzielnicy do lotniska Kraków-Balice. To nie jest czas dojazdu.'),
    ('population_total', 'Population', 'Liczba ludności', 'The number of people living in the district according to the statistical office. No data for Kraków: the city publishes only the number of people registered as permanent residents.', 'Liczba osób mieszkających w dzielnicy według urzędu statystycznego. Brak danych dla Krakowa: miasto publikuje tylko liczbę osób zameldowanych na pobyt stały.'),
    ('residents_registered', 'Registered permanent residents', 'Zameldowani na pobyt stały', 'People registered for permanent residence in the district. This is fewer than the people who really live there, because not everyone registers.', 'Osoby zameldowane w dzielnicy na pobyt stały. To mniej niż faktyczna liczba mieszkańców, bo nie każdy się melduje.'),
    ('population_density', 'Population density', 'Gęstość zaludnienia', 'How many people live on each square kilometre. For Kraków it is counted from registered residents, so the real figure is higher.', 'Ile osób mieszka na każdym kilometrze kwadratowym. Dla Krakowa liczone z osób zameldowanych, więc prawdziwa liczba jest wyższa.'),
    ('age_mean', 'Average age', 'Średni wiek', 'The average age of the registered residents of the district, counted from their year of birth.', 'Średni wiek zameldowanych mieszkańców dzielnicy, liczony z roku urodzenia.'),
    ('air_pm10_mean', 'Smog: PM10 dust (yearly average)', 'Smog: pył PM10 (średnia roczna)', 'The amount of fine PM10 dust in the air, a main part of smog, averaged over a year (the 12 months to August 2026). Less is better. Worked out from the nearest GIOŚ measuring stations, not measured at your door.', 'Ilość drobnego pyłu PM10 w powietrzu, głównego składnika smogu, średnio w ciągu roku (12 miesięcy do sierpnia 2026). Im mniej, tym lepiej. Wyliczona z najbliższych stacji pomiarowych GIOŚ, a nie zmierzona pod Twoim domem.'),
    ('air_pm25_mean', 'Smog: PM2.5 dust (yearly average)', 'Smog: pył PM2,5 (średnia roczna)', 'The amount of the finest PM2.5 dust in the air, which gets deepest into the lungs, averaged over a year (the 12 months to August 2026). Less is better. Worked out from the nearest GIOŚ measuring stations, not measured at your door.', 'Ilość najdrobniejszego pyłu PM2,5 w powietrzu, który najgłębiej wnika do płuc, średnio w ciągu roku (12 miesięcy do sierpnia 2026). Im mniej, tym lepiej. Wyliczona z najbliższych stacji pomiarowych GIOŚ, a nie zmierzona pod Twoim domem.'),
    ('air_no2_mean', 'Exhaust fumes: nitrogen dioxide NO₂ (yearly average)', 'Spaliny: dwutlenek azotu NO₂ (średnia roczna)', 'The amount of nitrogen dioxide in the air, a gas from car exhaust and heating, averaged over a year (the 12 months to August 2026). Less is better. Worked out from the nearest GIOŚ measuring stations, not measured at your door.', 'Ilość dwutlenku azotu w powietrzu, gazu ze spalin samochodów i ogrzewania, średnio w ciągu roku (12 miesięcy do sierpnia 2026). Im mniej, tym lepiej. Wyliczona z najbliższych stacji pomiarowych GIOŚ, a nie zmierzona pod Twoim domem.'),
    ('air_quality_index', 'Air quality now (scale 0-5)', 'Jakość powietrza teraz (skala 0–5)', 'The GIOŚ rating from 0 (very good) to 5 (very bad) at the latest reading, worked out from the nearest stations. It shows one moment, not the whole year.', 'Ocena GIOŚ od 0 (bardzo dobra) do 5 (bardzo zła) z ostatniego odczytu, wyliczona z najbliższych stacji. Pokazuje jedną chwilę, a nie cały rok.'),
    ('amenity_parks_share', 'Parks: share of the district', 'Parki: jaka część dzielnicy', 'How much of the district is taken by parks (OpenStreetMap). Forests and cemeteries are not counted.', 'Jaką część dzielnicy zajmują parki (OpenStreetMap). Lasy i cmentarze nie są liczone.'),
    ('noise_share_above_55db', 'Noise: share of the district above 55 dB', 'Hałas: jaka część dzielnicy głośniejsza niż 55 dB', 'How much of the district has a noise level of at least 55 decibels (dB) averaged over a day, on the city''s 2022 noise map (roads, railways and industry). Less is better.', 'Jaka część dzielnicy ma poziom hałasu co najmniej 55 decybeli (dB) średnio w ciągu doby, według miejskiej mapy hałasu z 2022 r. (drogi, kolej i przemysł). Im mniej, tym lepiej.'),
    ('night_noise_estimate', 'Night noise (estimate)', 'Hałas w nocy (szacunek)', 'An estimate from the number of bars and clubs and the share of loud areas, on a scale of 0 to 100: more means louder. It compares only the districts of Kraków.', 'Szacunek z liczby barów i klubów oraz udziału głośnych terenów, w skali od 0 do 100: więcej oznacza głośniej. Porównuje tylko dzielnice Krakowa.'),
    ('busyness_index', 'Crowds and traffic (estimate)', 'Tłok i ruch (szacunek)', 'An estimate from how many stops, departures, shops and nightlife places the district has, on a scale of 0 to 100: more means busier and more crowded. It compares only the districts of Kraków.', 'Szacunek z liczby przystanków, odjazdów, sklepów i lokali nocnych w dzielnicy, w skali od 0 do 100: więcej oznacza większy ruch i tłok. Porównuje tylko dzielnice Krakowa.'),
    ('walkability_index', 'Everyday needs close by (estimate)', 'Usługi codzienne blisko domu (szacunek)', 'An estimate of how much of daily life you can do on foot, from the number of supermarkets, schools, clinics and stops and the share of parks, on a scale of 0 to 100: more is better. It compares only the districts of Kraków.', 'Szacunek, ile codziennych spraw załatwisz pieszo, z liczby supermarketów, szkół, przychodni i przystanków oraz udziału parków, w skali od 0 do 100: więcej to lepiej. Porównuje tylko dzielnice Krakowa.'),
    ('family_friendliness_index', 'Friendliness to families with children (estimate)', 'Przyjazność dla rodzin z dziećmi (szacunek)', 'An estimate from the number of schools and nursery places, green space, tree cover, low noise and few accidents with pedestrians and cyclists, on a scale of 0 to 100: more is better. It compares only the districts of Kraków.', 'Szacunek z liczby szkół i miejsc w żłobkach, zieleni, drzew, niskiego hałasu i małej liczby wypadków z udziałem pieszych i rowerzystów, w skali od 0 do 100: więcej to lepiej. Porównuje tylko dzielnice Krakowa.'),
    ('heat_exposure_index', 'Summer heat (estimate)', 'Upał latem (szacunek)', 'An estimate from few trees and little green space, on a scale of 0 to 100: more means the district heats up more in summer. It compares only the districts of Kraków.', 'Szacunek z małej liczby drzew i niewielkiej ilości zieleni, w skali od 0 do 100: więcej oznacza, że dzielnica mocniej nagrzewa się latem. Porównuje tylko dzielnice Krakowa.'),
    ('safety_index', 'Road safety and reach of emergency services', 'Bezpieczeństwo na drogach i dostęp do służb', 'Put together from road accidents, street lighting and the distance to the police, fire station and hospital, on a scale of 0 to 100: more is better. For Kraków it holds no data on crime. It does not say whether an area is safe or not.', 'Złożone z wypadków drogowych, oświetlenia ulic i odległości do policji, straży pożarnej i szpitala, w skali od 0 do 100: więcej to lepiej. Dla Krakowa nie zawiera danych o przestępczości. Nie mówi, czy okolica jest bezpieczna.'),
    ('crimes_per_10k', 'Recorded crimes per 10,000 residents', 'Przestępstwa stwierdzone na 10 000 mieszkańców', 'Crimes recorded by the police per 10,000 residents in 2024. No data for Kraków: the city does not publish crime by district. Higher in districts with many visitors and commuters; it is not a measure of risk.', 'Przestępstwa stwierdzone przez policję na 10 000 mieszkańców w 2024 r. Brak danych dla Krakowa: miasto nie publikuje przestępstw według dzielnic. Wyższe w dzielnicach z wieloma odwiedzającymi i dojeżdżającymi; to nie jest miara ryzyka.'),
    ('crime_detection_rate', 'Offender detection rate', 'Wskaźnik wykrywalności sprawców', 'The share of recorded crimes in 2024 in which the offender was found. No data for Kraków: the city does not publish crime by district.', 'Odsetek przestępstw stwierdzonych w 2024 r., w których wykryto sprawcę. Brak danych dla Krakowa: miasto nie publikuje przestępstw według dzielnic.'),
    ('sale_price_median_m2', 'Typical flat price per m² (median)', 'Typowa cena mieszkania za m² (mediana)', 'The typical sale price of one square metre of a flat on the free market: half of the sales were cheaper, half dearer (the median). From the official Real Estate Price Register, 24 months to September 2026.', 'Typowa cena sprzedaży jednego metra kwadratowego mieszkania na wolnym rynku: połowa transakcji była tańsza, połowa droższa (mediana). Z oficjalnego Rejestru Cen Nieruchomości, 24 miesiące do września 2026.'),
    ('sale_transactions_count', 'Sales behind the price', 'Ile sprzedaży uwzględniono (cena sprzedaży)', 'The number of sales the typical price is worked out from. The more there are, the more reliable the figure.', 'Liczba sprzedaży, z których wyliczono typową cenę. Im więcej, tym pewniejsza liczba.'),
    ('rent_price_median_m2', 'Typical asking rent per m² a month (median)', 'Typowy czynsz ofertowy za m² miesięcznie (mediana)', 'The typical asking rent for one square metre a month, without extra charges: half of the offers were cheaper, half dearer (the median). From Otodom and OLX listings in one snapshot in September 2026, not signed contracts.', 'Typowa cena wynajmu jednego metra kwadratowego na miesiąc, bez opłat dodatkowych: połowa ofert była tańsza, połowa droższa (mediana). Z ogłoszeń Otodom i OLX z jednego zrzutu z września 2026, a nie z podpisanych umów.'),
    ('rent_listings_count', 'Rent offers behind the price', 'Ile ofert wynajmu uwzględniono', 'The number of rent offers the typical rent is worked out from, after removing repeats. The more there are, the more reliable the figure.', 'Liczba ofert wynajmu, z których wyliczono typowy czynsz, po usunięciu powtórzeń. Im więcej, tym pewniejsza liczba.'),
    ('road_accidents_per_km', 'Road accidents per km of road', 'Wypadki drogowe na km dróg', 'How many accidents with injured or killed people happen each year on every kilometre of road in the district (average of 2022 to 2024, police SEWiK data). Less is better.', 'Ile wypadków z rannymi lub zabitymi zdarza się rocznie na każdym kilometrze dróg w dzielnicy (średnia z lat 2022–2024, dane policji SEWiK). Im mniej, tym lepiej.'),
    ('livability_score_default', 'Overall score (default weights)', 'Wynik ogólny (wagi domyślne)', 'A comparison of the districts of Kraków from public data: transport, prices, noise, green space and more. The score from 0 to 100 shows where a district stands among the others: higher is a better place in this comparison. It is not a judgement of what living there is like. High flat prices lower the score. You can change the weights on the page Find a district.', 'Porównanie dzielnic Krakowa na podstawie danych publicznych: komunikacja, ceny, hałas, zieleń i inne. Wynik od 0 do 100 pokazuje, jakie miejsce zajmuje dzielnica wśród pozostałych: wyższy to lepsze miejsce w tym porównaniu. To nie jest ocena tego, jak się tam żyje. Wysokie ceny mieszkań obniżają wynik. Wagi możesz zmienić na stronie Znajdź dzielnicę.')
  ) as v(metric_key, label_en, label_pl, description_en, description_pl)
 where m.metric_key = v.metric_key
   and (m.label_en, m.label_pl, m.description_en, m.description_pl) is distinct from (v.label_en, v.label_pl, v.description_en, v.description_pl);
